modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/impleri/player-skills/issues"
license = "MIT"

[[mods]]
modId = "playerskills"
version = "${version}"
displayName = "Player Skills"
authors = "impleri"
description = '''
A library mod that provides a baseline implementation of player-specific skills.
'''
#logoFile = ""

[[dependencies.playerskills]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.playerskills]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.playerskills]]
modId = "architectury"
mandatory = true
versionRange = "[6.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.playerskills]]
modId = "kubejs"
mandatory = false
versionRange = "[1902.6,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.playerskills]]
modId = "crafttweaker"
mandatory = false
versionRange = "[10.1,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.playerskills]]
modId = "ftb-teams"
mandatory = false
versionRange = "[1902.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.playerskills]]
modId = "ftb-quests"
mandatory = false
versionRange = "[1902.0,)"
ordering = "AFTER"
side = "BOTH"
