org.gradle.jvmargs=-Xmx4G
maven_group=net.impleri
minecraft_major_version=1.19
minecraft_version=1.19.2
scala_major_version=2.13
scala_version=2.13.10
slp_version=1.0.0
slp_build=10
cats_version=2.10.0
scalatest_version=3.2.18
mockito_version=1.17.30
#scala_forge_version=2.13.10
#slp_forge_version=10
# Architectury-related config
enabled_platforms=fabric,forge
archives_base_name=playerskills
architectury_version=6.6.92
# Fabric config
fabric_loader_version=0.15.7
fabric_api_version=0.77.0
# Forge config
forge_version=43.2.0
# KubeJS config
#kubejs_version=1902.6.0-build.142
#rhino_version=1902.2.2-build.264
# CraftTweaker config
#crafttweaker_version=10.1.41
# FTB Teams Integration
ftb_teams_version=1902.2.12-build.91
# FTB Quests Integration
ftb_quests_version=1902.4.11-build.207
# REI Integration
rei_version=9.1.682
# JEI Integration
jei_version=11.6.0.1019
# Curios Integration
curios_version=5.1.2.2
# Trinkets Integration
trinkets_version=3.4.1
# WTHIT Integration
badpackets_version=0.2.3
wthit_version=5.31.0
# TheOneProbe Integration
top_version=6.2.0-6
# Jade Integration 8.9.2
jade_version=4914105
