name: 'Versioning Label'
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
jobs:
  add_label:
    uses: impleri/automatic-skills/.github/workflows/add-label.yml@main
    if: ${{ github.event.action == 'opened' }}
  check_labels:
    uses: impleri/automatic-skills/.github/workflows/check-labels.yml@main
    if: ${{ github.event.action != 'opened' }}
